default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: LambOverice_development

test:
  <<: *default
  database: LambOverice_test

production:
  <<: *default
  database: LambOverice_production
  username: LambOverice
  password: <%= ENV['LAMBOVERICE_DATABASE_PASSWORD'] %>
